
version: 2

models:
    - name: table1
      description: "A starter dbt model"
    - name: table2
      description: "A starter dbt model"
    - name: table3
      columns:
      - name: "No of employees"
        tests:
        - not_null
      description: "For testing"
